version: "3.3"
services:
  fastmovie-scrapper:
      build: .
      restart: always
      privileged: true
      container_name: fastmovie-scrapper
      logging:
        driver: "json-file"
        options:
          max-size: 10m
          max-file: "3"
          labels: "production_status"
          env: "os"
      labels:
        production_status: "testing"
      environment:
        - os=ubuntu
      volumes:
        - /root/projects/scrapper/fastmovie-scrapper:/usr/src/app/scrapper