
FROM python:3.8-slim-buster


WORKDIR /app

COPY . .

RUN pip3 install -r requirements.txt

RUN export PATH=$PATH:/app/geckodriver

RUN export PYTHONIOENCODING=utf8

RUN python3 digimovie-moviedownloadScrapper.py